### ISSUE TITLE
Compile issues with ESPHome 2024.2.0

### ISSUE THREAD

**Issue by stflink** [psvanstrom/esphome-uh50reader#4]
Hi,

Thanks for the project.
Trying to get it to work for me but I'm not able to compile in ESPHome 2024.2.0, fails with the error below.
Any pointers to what might need to be changed to get it to compile?

```
INFO ESPHome 2024.2.0
INFO Reading configuration /config/esphome/uh50reader.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing uh550 (board: d1_mini; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
Compiling .pioenvs/uh550/src/main.cpp.o
Archiving .pioenvs/uh550/lib3ff/libESP8266mDNS.a
Archiving .pioenvs/uh550/libFrameworkArduinoVariant.a
Compiling .pioenvs/uh550/FrameworkArduino/Crypto.cpp.o
Compiling .pioenvs/uh550/FrameworkArduino/Esp-frag.cpp.o
In file included from src/main.cpp:30:
src/uh50reader.h:50:80: error: expected class-name before '{' token
   50 | class UH50Reader : public Component, public UARTDevice, public CustomAPIDevice {
      |                                                                                ^
src/uh50reader.h: In member function 'virtual void UH50Reader::setup()':
src/uh50reader.h:67:7: error: 'register_service' was not declared in this scope
   67 |       register_service(&UH50Reader::read_meter, "start_read_meter");
      |       ^~~~~~~~~~~~~~~~
*** [.pioenvs/uh550/src/main.cpp.o] Error 1
========================== [FAILED] Took 2.40 seconds ==========================
```

**Comment by alfs** [comment]
@stflink do you still have this problem with updated ESPHome versions?
Project compiles fine with ESPHome 2024.9 for me.

**Comment by stflink** [comment]
@alfs Thanks for the answer, I'll give it another go.

**Comment by stflink** [comment]
Works fine to compile with ESPHome 2024.9.1. Thanks again.
